add_executable(07_instanced main.c)
target_link_libraries(07_instanced PRIVATE bielik bk_warnings)
bk_stage_shaders(07_instanced)

add_executable(07_instanced_run main.c)
target_link_libraries(07_instanced_run PRIVATE bielik bk_warnings)
target_compile_definitions(07_instanced_run PRIVATE BK_MAIN_HANDLED)
bk_stage_shaders(07_instanced_run)
